<?xml version="1.0"?>
<!--Jack Wason 6780957-->
<!DOCTYPE audit [
    <!ELEMENT audit (subject)>
    <!ELEMENT subject (code, title, statistics)>
    <!ATTLIST subject sid CDATA #REQUIRED>
    <!ELEMENT code (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT statistics (enrol, withdrawn)>
    <!ELEMENT enrol (#PCDATA)>
    <!ELEMENT withdrawn (#PCDATA)>
]>
<audit campus="Woolloomooloo" year="2000" session="A">
    <subject sid="0769642">
        <code>MATH101</code>
        <title>Calculus</title>
        <statistics>
            <enrol>170</enrol>
            <withdrawn>31</withdrawn>
        </statistics>
    </subject>
    <subject sid="1734231">
        <code>MATH234</code>
        <title>Abstract Algebre</title>
        <statistics>
            <enrol>40</enrol>
            <withdrawn>15</withdrawn>
        </statistics>
    </subject>
</audit>